version: '3.8'

networks:
  scantether_network:
    name: my_scantether_network

services:
  telegram-bot:
    build: ./telegram-bot
    container_name: bot_scantether
    restart: always
    networks:
      - scantether_network
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MONGODB_URI=mongodb://mongodb_scantether/
    depends_on:
      - mongodb_scantether

  data-scraper:
    build: ./data-scraper
    container_name: data_scraper_scantether
    restart: always
    networks:
      - scantether_network
    environment:
      - MONGODB_URI=mongodb://mongodb_scantether/
    depends_on:
      - mongodb_scantether

  mongodb_scantether:
    image: mongo:latest
    container_name: mongodb_scantether
    restart: always
    networks:
      - scantether_network
    volumes:
      - ./mongodb/data:/data/db
