version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: scantether_redis
    restart: always
    networks:
      - scantether_network

  api:
    build: .
    container_name: scantether_api
    restart: always
    depends_on:
      - redis
    networks:
      - scantether_network
    # 由于没有暴露端口，外部访问可通过内网代理或反向代理来实现
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  poller:
    build: .
    container_name: scantether_poller
    restart: always
    depends_on:
      - redis
    networks:
      - scantether_network
    command: python -m app.poller

  celery:
    build: .
    container_name: scantether_celery
    restart: always
    depends_on:
      - redis
    networks:
      - scantether_network
    command: celery -A app.tasks.celery_app worker --loglevel=info

  telegram_bot:
    build: .
    container_name: scantether_bot
    restart: always
    networks:
      - scantether_network
    command: python -m app.telegram_bot

networks:
  scantether_network:
    external: true 